// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvpplnpsnvxxyrprhzkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2cHBsbnBzbnZ4eHlycHJoemtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzMzUyOTQsImV4cCI6MjA4NzkxMTI5NH0.zxuanPiiEEK1K02lFHEs1lWo4bc64n3Rnjd3usgyJuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});